linters-settings:
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option.
    # Default: 120.
    line-length: 95
  gofmt:
    simplify: true
linters:
  enable:
    - lll
    - gofmt
    - gosec
    - nolintlint