# fly.toml app configuration file generated for pedro-go on 2024-02-05T19:46:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pedro-go'
primary_region = 'ams'

[mounts]
  source="pedrovolume"
  destination="/data"

[env]
  DSN = "/data/pedro.db"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
