### Add wish
POST http://localhost:8080/gifts/wishes

### Add sweet
POST http://localhost:8080/gifts/sweets

### Add image

POST http://localhost:8080/gifts/images?url=https%3A%2F%2Fphotos.app.goo.gl%2yeeet

### Redeem image

GET http://localhost:8080/gifts/redeem?id=01929b8c-0a5b-7459-be04-49fb9930af5a